export const ApiMaster = {
  businessUnit: 'MasterBusinessUnit',
  businessUnitSave: 'MasterBusinessUnit/doSave',
  groupRole: 'MasterGroupRole',
  groupRoleSave: 'MasterGroupRole/doSave',
  groupRoleMenu: 'MasterGroupRole/getMenu',
  user: 'MasterUser',
  userSave: 'MasterUser/doSave',
  userGroupRole: 'MasterUser/getGroupRole',
  userBinusian: 'MasterUser/getBinusian',
  pic: 'MasterPIC',
  picSave: 'MasterPIC/doSave',
  picCompany: 'MasterPIC/getCompanyList',
  picSchool: 'MasterPIC/getHighschoolList',
  rewardLevel: 'MasterRewardLevel',
  rewardLevelSave: 'MasterRewardLevel/doSave',
  category: 'MasterRewardCategory',
  categorySave: 'MasterRewardCategory/doSave',
  categoryBusinessUnit: 'MasterRewardCategory/getBusinessUnit',
  product: 'MasterRewardProduct',
  productSave: 'MasterRewardProduct/doSave',
  productCategory: 'MasterRewardProduct/getRewardCategory',
  news: 'MasterNews',
  newsSave: 'MasterNews/doSave',
  reference: 'MasterReference',
  referenceSave: 'MasterReference/doSave',
}
